modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/EpicSquid/SuperiorShields/issues"
license = "MIT"
[[mods]]
modId = "superiorshields"
version = "${file.jarVersion}"
displayName = "Superior Shields"
displayURL = "https://minecraft.curseforge.com/projects/superiorshields"
credits = "The various contributors of shield textures for compatible mods."
authors = "EpicSquid"
description = '''
Who needs shields when you have these? Borderlands style shields for Minecraft.
'''
[[dependencies.superiorshields]]
modId = "forge"
mandatory = true
versionRange = "[43.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.superiorshields]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.superiorshields]]
modId = "curios"
mandatory = true
versionRange = "[FORGE-1.19.2-5.1.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.superiorshields]]
modId = "botania"
mandatory = false
versionRange = "[1.19.2-436,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.superiorshields]]
modId = "thermal"
mandatory = false
versionRange = "[10.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.superiorshields]]
modId = "malum"
mandatory = false
versionRange = "[1.5.1,)"
ordering = "NONE"
side = "BOTH"